spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create # create는 애플리케이션 실행시점에 테이블을 drop하고 다시 만든다.
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # in 쿼리의 개수. n + 1 문제에서 어느정도 해방이 가능

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace